## common properties
server:
  port: 8080
  shutdown: graceful

file:
  save:
    path: C:\Program Files\workplace\FileTmp

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rsupport
    username: root
    password: leehyeock=12
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
